### ISSUE TITLE
add still_on_track function

### ISSUE THREAD

**Issue by generationmake** [wuehr1999/NavigationOnArduino#1]
Hi.
Add a function to check if my positon (C) ist still on track from point A to B and for example calculate how much meters I am off the track. Could be useful to determine if recalculation of waypoints is necessary.

**Comment by wuehr1999** [comment]
Hi @generationmake ,
I added this function: `calculateDistanceFromTrack(NavPoint trackpoint1, NavPoint trackpoint2)`, which takes the two waypoints defining Your track line and returns the offset of the current point in meters.
