### ISSUE TITLE
add function to calculate difference between two bearings/headings

### ISSUE THREAD

**Issue by generationmake** [wuehr1999/NavigationOnArduino#2]
You often have to subtract two bearings/heading from each other for example to calculate if you are still on route. The problem is that the course is limited to 0 to 360 degrees or -180 to +180 degress. So when your two bearings are for example  170 and -165 degrees, the difference is not 335 but -25 degrees. The function should handle this. 
Additionally it would be cool if the function works independant of the initial values beeing limited to -180 to 180 or 0 to 360 degrees.

**Comment by wuehr1999** [comment]
Hi @generationmake,
I added the function `calculateDeltaAngle(float courseHeading, NavPoint destinationPoint)` and I am pretty sure that this is what You need. The function takes a destination point  and Your course heading ( -180 to 180 or 0 to 360  should not be relevant ) and returns the delta to update the course.
