### ISSUE TITLE
Move osmfileToStringTool into subfolder extras

### ISSUE THREAD

**Issue by aentinger** [wuehr1999/NavigationOnArduino#5]
In order to be compliant with the Arduino Library standard I recommend to move the folder `osmfileToStringTool` into a newly created subfolder `extras`.

(Found that repo because @generationmake mentioned it to me via Email).

**Comment by wuehr1999** [comment]
Hi @aentinger 
thank You for Your feedback. 
I just moved the tool the the extras folder and will close the issue.
